#ifndef COMPONENT_IDS_H_INCLUDED
#define COMPONENT_IDS_H_INCLUDED

enum class COMPONENT_IDS
{
    AMMO_PICKUP = 0,
    HEALTH_PICKUP = 1,
    NUM_COMPONENT_IDS = 2
};

#endif // COMPONENT_IDS_H_INCLUDED

