CC = g++
CFLAGS = -std=c++11 -g
INCDIRS = 
LIBDIRS = 
LIBS = 
SOURCES = main.cpp             \
          ProcessManager.cpp   \
          Process.cpp          \
          DelayProcess.cpp     \
          KaboomProcess.cpp
TARGET = main

all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(TARGET) $(INCDIRS) $(LIBDIRS) $(LIBS)

