#include <EventData.h>

// Global unique identifier (GUID); generated by something like from within visual studio
const EventType EvtDataNewActor::sk_EventType(0x77DD2B30);
const EventType EvtDataRemoteEnvironmentLoaded::sk_EventType(0x77DD2B31);
const EventType EvtDataEnvironmentLoaded::sk_EventType(0x77DD2B32);
const EventType EvtDataDestroyActor::sk_EventType(0x77DD2B33);
const EventType EvtDataRequestDestroyActor::sk_EventType(0x77DD2B34);
const EventType EvtDataRequestNewActor::sk_EventType(0x77DD2B35);
const EventType EvtDataMoveActor::sk_EventType(0x77DD2B36);

