CC = g++
CFLAGS = -std=c++17 -g
INCDIRS = -I./
LIBDIRS = 
LIBS = 
SOURCES = main.cpp EventData.cpp EventManager.cpp
TARGET = main

all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(TARGET) $(INCDIRS) $(LIBDIRS) $(LIBS)

