CC = g++
CFLAGS = -std=c++11 -g
INCDIRS = -I./
LIBDIRS = 
LIBS = -lz
SOURCES = main.cpp \
          ZipFile.cpp
TARGET = main

all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(TARGET) $(INCDIRS) $(LIBDIRS) $(LIBS)

