CC = g++
CFLAGS = -std=c++11 -g
INCDIRS = -I./
LIBDIRS = 
LIBS =
SOURCES = main.cpp       \
          Resource.cpp   
TARGET = main

all:
	$(CC) $(CFLAGS) $(SOURCES) -o $(TARGET) $(INCDIRS) $(LIBDIRS) $(LIBS)

